# Generated by Django 5.2.5 on 2025-08-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('papel', models.CharField(choices=[('gestor', 'Gestor'), ('colaborador', 'Colaborador')], max_length=15)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='core.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('descricao', models.TextField(verbose_name='Qual é a dor ou oportunidade?')),
                ('tipo_beneficio', models.CharField(choices=[('horas_erros', 'Horas/Erros'), ('receita', 'Receita'), ('satisfacao_nps', 'Satisfação/NPS'), ('compliance', 'Compliance'), ('outro', 'Outro')], max_length=30)),
                ('alinhamento_okr', models.CharField(choices=[('prosperar', 'Prosperar nos negócios'), ('reter_clientes', 'Conquistar e reter clientes'), ('excelencia', 'Gerir com excelência'), ('desenvolver_profissionais', 'Desenvolver profissionais capacitados e senso de pertencimento'), ('outros', 'Outros')], max_length=50)),
                ('esforco_estimado', models.CharField(choices=[('baixo', 'Baixo (<1 semana)'), ('medio', 'Médio (1-4 semanas)'), ('alto', 'Alto (>4 semanas)')], max_length=10)),
                ('risco_outro_descricao', models.CharField(blank=True, help_text="Obrigatório se marcar 'Outro' nos riscos.", max_length=200, null=True)),
                ('metrica_sucesso', models.TextField(blank=True)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipes_necessarias', models.ManyToManyField(blank=True, help_text='Departamentos necessários para execução da ideia.', related_name='ideias_com_equipe', to='core.departamento')),
                ('patrocinador', models.ForeignKey(blank=True, limit_choices_to={'papel': 'gestor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideias_patrocinadas', to='core.colaborador')),
                ('publicos_impactados', models.ManyToManyField(blank=True, help_text='Departamentos afetados por essa ideia.', related_name='ideias_afetadas', to='core.departamento')),
                ('riscos_identificados', models.ManyToManyField(blank=True, related_name='ideias', to='core.risco')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
    ]
