# Generated by Django 5.2.5 on 2025-08-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colaborador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='status',
            field=models.CharField(choices=[('avaliacao', 'Em Avaliação'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], default='Em Avaliação', max_length=20),
        ),
    ]
