# Generated by Django 5.2.5 on 2025-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ideia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='classificacao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ideia',
            name='esforco_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ideia',
            name='valor_total',
            field=models.IntegerField(default=0),
        ),
    ]
